const mongoose = require("mongoose");
const Item = require("./schemas/Item");
const mongo = require("./mongo");
const dotenv = require("dotenv");
dotenv.config();

let items = [
  {
    name: "Strawberry",
    icon: "1005102951834067036",
    slug: "strawberry",
    description: "A tasty fruit that can be used to make tasty desserts.",
    effects: ["Restores 10 HP"],
    buyPrice: 50,
    sellPrice: 10,
    rarity: "common",
    fromGuild: "YEET",
    usable: true,
    category: "item",
  },
  {
    name: "Newton's Banana",
    icon: "1005102614335205487",
    slug: "newtonbanana",
    description: "A Juicy Fruit That Was Taken Out Of Newton's Pants.",
    effects: ["Has A 2x Chance Of Getting Better Begs"],
    buyPrice: 1000,
    sellPrice: 10,
    rarity: "epic",
    fromGuild: "YEET",
    usable: false,
    category: "item",
  },
  {
    name: "Rotten Apple",
    icon: "1005103482090561586",
    slug: "rottenapple",
    description: "Makes You Smell Bad.",
    effects: [
      "Lowers Chances Of Getting Begs",
      "Lowers Chances Of Getting A Job",
    ],
    buyPrice: 0,
    sellPrice: -1000,
    rarity: "rare",
    fromGuild: "YEET",
    usable: false,
    category: "collectable",
  },
  {
    name: "Panties",
    icon: "1005107326459588709",
    slug: "panties",
    description:
      "A Women's Panties. Found After You Manage To Get A Girlfriend.",
    effects: ["Increases Childrens Limit To 2", "Refills Entire HP"],
    buyPrice: 0,
    sellPrice: 3000,
    rarity: "epic",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
  },
  {
    name: "Headphones",
    icon: "1005109346310561842",
    slug: "headphones",
    description: "Found In The Singer Job.",
    effects: [
      "Doubles Your Balance After Resigning For Singer Job As a Compensation",
      "Refills Entire HP",
    ],
    buyPrice: 0,
    sellPrice: 0,
    rarity: "epic",
    fromGuild: "YEET",
    usable: true,
    category: "collectable",
  },
  {
    name: "Duck",
    icon: "1009965196695052429",
    slug: "duck",
    description:
      "A Quack. Can Be Found In The Pond By Using The `fish` Command.",
    effects: [],
    buyPrice: 100,
    sellPrice: 50,
    rarity: "common",
    fromGuild: "YEET",
    keywords: ["fishItem"],
    usable: false,
    category: "item",
  },
  {
    name: "Beer",
    icon: "1009967255196545024",
    slug: "beer",
    description:
      "Take Out Some Time For Some Chillin'. Can Be Found In The Bar through the `drink` Command.",
    effects: [
      "Makes You Feel Good & Energetic",
      "Restores 30 HP",
      "You Will Be Immune To Robbery For 5 Mins",
    ],
    buyPrice: 0,
    sellPrice: 0,
    rarity: "rare",
    fromGuild: "YEET",
    usable: true,
    category: "collectable",
  },
  {
    name: "Bean",
    icon: "1009976621320650862",
    slug: "bean",
    description: "A Bean. Just As GOD Intended. Found In The Farmer Job.",
    effects: ["Either Doubles Or Halves Your Bank Account Limit When Used."],
    buyPrice: 0,
    sellPrice: 0,
    rarity: "rare",
    fromGuild: "YEET",
    usable: true,
    category: "collectable",
  },
  {
    name: "Gold Fish",
    icon: "1009978034067091527",
    slug: "gold_fish",
    description: "A Gold Fish From The Royal Pond. Found In The Fish Command.",
    effects: [],
    buyPrice: 0,
    sellPrice: 1000,
    rarity: "rare",
    fromGuild: "YEET",
    keywords: ["fishItem"],
    usable: false,
    category: "sellable",
  },
  {
    name: "Arctic Fish",
    icon: "1009978061648834611",
    slug: "arctic_fish",
    description:
      "A Highly Rare Fish, Only True Yeeters Can Find This. Found In The Fish Command.",
    effects: [],
    buyPrice: 0,
    sellPrice: 10000,
    rarity: "legendary",
    fromGuild: "YEET",
    keywords: ["fishItem"],
    usable: false,
    category: "sellable",
  },
  {
    name: "Fish Bone",
    icon: "1009978474699706408",
    slug: "fish_bone",
    description: "An Item Of Bad Luck. Found In The Fish Command.",
    effects: [],
    buyPrice: 0,
    sellPrice: -1000,
    rarity: "common",
    fromGuild: "YEET",
    keywords: ["fishItem"],
    usable: false,
    category: "sellable",
  },
  {
    name: "Baby Octopus",
    icon: "1009978646766817300",
    slug: "baby_octopus",
    description: "A Baby Octopus. Found In The Fish Command.",
    effects: [],
    buyPrice: 0,
    sellPrice: 2000,
    rarity: "rare",
    fromGuild: "YEET",
    keywords: ["fishItem"],
    usable: false,
    category: "sellable",
  },
  {
    name: "Cute Crab",
    icon: "1009978756179439646",
    slug: "cute_crab",
    description: "A Cute Crab. Found In The Fish Command.",
    effects: [],
    buyPrice: 0,
    sellPrice: 2000,
    rarity: "rare",
    fromGuild: "YEET",
    keywords: ["fishItem"],
    usable: false,
    category: "sellable",
  },
  {
    name: "Rotten Shoe",
    icon: "1009982111291285565",
    slug: "rotten_shoe",
    description:
      "Perhaps You Shouldn't Be Wearing This. Found In The Fish Command.",
    effects: ["More Chances Of Getting Begs"],
    buyPrice: 1000,
    sellPrice: 500,
    rarity: "common",
    fromGuild: "YEET",
    keywords: ["fishItem"],
    usable: false,
    category: "item",
  },
  {
    name: "Fishing Rod",
    icon: "1009983198387777667",
    slug: "fishing_rod",
    description:
      "An Exotic Piece From Darked's Pants. Enables The `/fish` command",
    effects: ["Enables You To Use The `fish` Command"],
    buyPrice: 3000,
    sellPrice: 500,
    rarity: "common",
    fromGuild: "YEET",
    usable: false,
    category: "tool",
  },
  {
    name: "Bow",
    icon: "1015570180782440499",
    slug: "bow",
    description:
      "Darked Satisfies His Girl With This. Enables The `/hunt` command",
    effects: ["Enables You To Use The `hunt` Command"],
    buyPrice: 3000,
    sellPrice: 500,
    rarity: "common",
    fromGuild: "YEET",
    usable: false,
    category: "tool",
  },
  {
    name: "Hedgehog",
    icon: "1015581928931479563",
    slug: "hedgehog",
    description: "A Small Hedgehog",
    effects: [],
    buyPrice: 0,
    sellPrice: 500,
    rarity: "common",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },
  {
    name: "Squirrel",
    icon: "1015581657132171325",
    slug: "squirrel",
    description: "A Witty Squirrel",
    effects: [],
    buyPrice: 0,
    sellPrice: 500,
    rarity: "common",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },
  {
    name: "Owl",
    icon: "1015585668841357342",
    slug: "owl",
    description: "A Quiet Owl",
    effects: [],
    buyPrice: 0,
    sellPrice: 500,
    rarity: "common",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },
  {
    name: "Ant",
    icon: "1015586081955139644",
    slug: "ant",
    description: "A Hard (Working) Ant",
    effects: [],
    buyPrice: 0,
    sellPrice: 500,
    rarity: "common",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },
  {
    name: "Lizard",
    icon: "1015586492388749408",
    slug: "lizard",
    description: "A Seducing Lizard",
    effects: [],
    buyPrice: 0,
    sellPrice: 500,
    rarity: "common",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  // Rare Hunt Items
  {
    name: "Rabbit",
    icon: "1015587229814509608",
    slug: "rabbit",
    description: "A Fast Rabbit",
    effects: [],
    buyPrice: 0,
    sellPrice: 1000,
    rarity: "rare",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  {
    name: "Pigeon",
    icon: "1015587666319904809",
    slug: "pigeon",
    description: "A Bird That Can Fly (obv.)",
    effects: [],
    buyPrice: 0,
    sellPrice: 1000,
    rarity: "rare",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  {
    name: "Bat",
    icon: "1015588221213749299",
    slug: "bat",
    description: "Rare Cuz You Need To Find Them At Night..",
    effects: [],
    buyPrice: 0,
    sellPrice: 1000,
    rarity: "rare",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  {
    name: "Mosquito",
    icon: "1015588806386274395",
    slug: "mosquito",
    description: "Bloody Sucker",
    effects: [],
    buyPrice: 0,
    sellPrice: 1000,
    rarity: "rare",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  {
    name: "Porcupine",
    icon: "1015589373699428402",
    slug: "porcupine",
    description: "An Abnormal Porcupine",
    effects: [],
    buyPrice: 0,
    sellPrice: 1000,
    rarity: "rare",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  // Epic Items For Hunt
  {
    name: "House Fly",
    icon: "1015589829796429824",
    slug: "fly",
    description: "CATCH THIS IF YOU CAN!!!!",
    effects: [],
    buyPrice: 0,
    sellPrice: 1500,
    rarity: "epic",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  {
    name: "Normal Panda",
    icon: "1015590273205678170",
    slug: "panda",
    description: "Feed Him Your Bamboo :)",
    effects: [],
    buyPrice: 0,
    sellPrice: 1500,
    rarity: "epic",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  {
    name: "Foxy",
    icon: "1015590928917991475",
    slug: "foxy",
    description: "Its FOXY Not fox",
    effects: [],
    buyPrice: 0,
    sellPrice: 1500,
    rarity: "epic",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  {
    name: "Monkey",
    icon: "1015591488207470715",
    slug: "monkey",
    description: "A Naughty Red-Ass Monkey",
    effects: [],
    buyPrice: 0,
    sellPrice: 1500,
    rarity: "epic",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  {
    name: "Seal",
    icon: "1015591933701259294",
    slug: "seal",
    description: "A Sealed Seal. Nothing Less, Nothing More :)",
    effects: [],
    buyPrice: 0,
    sellPrice: 1500,
    rarity: "epic",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  // Legendary Items For Hunt
  {
    name: "Lion",
    icon: "1015593437619290203",
    slug: "lion",
    description: "The King Himself",
    effects: [],
    buyPrice: 0,
    sellPrice: 100000,
    rarity: "legendary",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  {
    name: "Bear",
    icon: "1015593458100080701",
    slug: "bear",
    description: "Big Bear :D",
    effects: [],
    buyPrice: 0,
    sellPrice: 5000,
    rarity: "legendary",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  {
    name: "Elephant",
    icon: "1015593447828246569",
    slug: "elephant",
    description: "My Elephant Jumbo",
    effects: [],
    buyPrice: 0,
    sellPrice: 7000,
    rarity: "legendary",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  {
    name: "Gorilla",
    icon: "1015593412755464273",
    slug: "gorilla",
    description: "Gorillas Are Going Way To Open.. :(",
    effects: [],
    buyPrice: 0,
    sellPrice: 7000,
    rarity: "legendary",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  {
    name: "Camel",
    icon: "1015593719912734770",
    slug: "camel",
    description: "A Hard Working Camel",
    effects: [],
    buyPrice: 0,
    sellPrice: 5000,
    rarity: "legendary",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  {
    name: "Orangutan",
    icon: "1015593468048965714",
    slug: "orangutan",
    description: "Gorilla's Brother (P.S: I didn't study bio)",
    effects: [],
    buyPrice: 0,
    sellPrice: 8000,
    rarity: "legendary",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  {
    name: "Jelly Fish",
    icon: "1015593923613294613",
    slug: "jelly_fish",
    description: "Would Love To Pee On A Girl Bitten By A Jelly Fish :)",
    effects: [],
    buyPrice: 0,
    sellPrice: 10000,
    rarity: "legendary",
    fromGuild: "YEET",
    usable: false,
    category: "sellable",
    keywords: ["hunt_item"],
  },

  {
    name: "Criminal Mind",
    icon: "1016489655375499294",
    slug: "criminal_mind",
    description: "Darked Was Born With This. Enables The `/crime` Command",
    effects: [],
    buyPrice: 0,
    sellPrice: 0,
    rarity: "common",
    fromGuild: "YEET",
    usable: false,
    category: "tool",
    keywords: [],
  },

  {
    name: "Life Saver",
    icon: "1016572351380459561",
    slug: "life_saver",
    description:
      "A Pair Of Angel Wings & A Divine Halo. Prevents Death. Used Up When You Die.",
    effects: ["Prevents Death"],
    buyPrice: 100000,
    sellPrice: 1000,
    rarity: "legendary",
    fromGuild: "YEET",
    usable: false,
    category: "power-up",
    keywords: [],
  },

  {
    name: "Limit Increaser Key",
    icon: "1017975426364227635",
    slug: "limit_increaser_key",
    description: "A Key Which Magically Increases Your Bank Account Limit!",
    effects: ["Increases Bank Account Limit By 50% Of The Current Limit"],
    buyPrice: 3000,
    sellPrice: 0,
    rarity: "rare",
    fromGuild: "YEET",
    usable: false,
    category: "item",
    keywords: [],
  },

  {
    name: "Armpit Hair",
    icon: "1018470987517403136",
    slug: "armpit_hair",
    description: "Harvested Weekly From Darked's Armpits",
    effects: [],
    buyPrice: 1_500_000,
    sellPrice: 300_000,
    rarity: "legendary",
    fromGuild: "YEET",
    usable: false,
    category: "collectable",
    keywords: [],
  },

  {
    name: "Robber's List",
    icon: "1020795110855823491",
    slug: "robber_list",
    description: "A List That Helps You See Robabble Users",
    effects: [],
    buyPrice: 10_000,
    sellPrice: 1000,
    rarity: "rare",
    fromGuild: "YEET",
    usable: true,
    category: "tool",
    keywords: [],
  },

  {
    name: "Padlock",
    icon: "1021505580336156772",
    slug: "padlock",
    description:
      "Prevents Someone From Robbing You.. But Can Be Broken While Robberry!",
    effects: [],
    buyPrice: 50_000,
    sellPrice: 1000,
    rarity: "rare",
    fromGuild: "YEET",
    usable: false,
    category: "tool",
    keywords: [],
  },

  {
    name: "Electric Lock",
    icon: "1021506732440174592",
    slug: "electric_lock",
    description:
      "Prevents Robbery, More Stronger Than Padlock, Also Gives A Shock To Whoever Tries To Steal!",
    effects: [],
    buyPrice: 300_000,
    sellPrice: 500,
    rarity: "legendary",
    fromGuild: "YEET",
    usable: false,
    category: "tool",
    keywords: [],
  },

  {
    name: "Fake ID",
    icon: "1021519059981971546",
    slug: "fake_id",
    description: "Disguises You On The Robbers List for 24h!",
    effects: [],
    buyPrice: 100_00_000,
    sellPrice: 500,
    rarity: "legendary",
    fromGuild: "YEET",
    usable: false,
    category: "tool",
    keywords: [],
  },

  {
    name: "Rob Book",
    icon: "1021533340785983508",
    slug: "rob_book",
    description:
      "A Book Containing Several Robbing Tips. Doubles Your Luck While Robbing",
    effects: ["Doubles Your Luck While Robbing"],
    buyPrice: 100_00_000_00,
    sellPrice: 500,
    rarity: "legendary",
    fromGuild: "YEET",
    usable: false,
    category: "power-up",
    keywords: [],
  },
];

async function insertItems() {
  await mongo().then(async (mongoose) => {
    try {
      console.log("Connected to mongo!!");
      await Item.deleteMany({});
      for (let item of items) {
        let itemData = await Item.findOne({ slug: item.slug });
        if (!itemData) {
          await new Item(item).save();
          console.log(`Saved ${item.name}`);
        } else {
          console.log(`${item.name} already exists`);
        }
      }
    } finally {
      // mongoose.connection.close();
    }
  });
}

insertItems();
