const things = [
  ...new Set([
    'rug',
    'toothbrush',
    'remote',
    'grid paper',
    'piano',
    'scotch tape',
    'twezzers',
    'tire swing',
    'ipod',
    'playing card',
    'clamp',
    'mouse pad',
    'chalk',
    'drawer',
    'shoe lace',
    'cookie jar',
    'model car',
    'conditioner',
    'hair tie',
    'sketch pad',
    'USB drive',
    'box',
    'washing machine',
    'shoes',
    'rusty nail',
    'rubber band',
    'helmet',
    'controller',
    'cork',
    'eraser',
    'seat belt',
    'stockings',
    'computer',
    'video games',
    'clay pot',
    'television',
    'checkbook',
    'soap',
    'clock',
    'shirt',
    'water bottle',
    'food',
    'camera',
    'blouse',
    'greeting card',
    'plate',
    'keyboard',
    'lamp shade',
    'headphones',
    'sidewalk',
    'sofa',
    'eye liner',
    'bracelet',
    'pool stick',
    'bananas',
    'canvas',
    'toe ring',
    'speakers',
    'sticky note',
    'mp3 player',
    'candle',
    'soy sauce packet',
    'packing peanuts',
    'keys',
    'spring',
    'house',
    'paint brush',
    'glass',
    'stop sign',
    'apple',
    'pillow',
    'plastic fork',
    'bookmark',
    'shampoo',
    'shawl',
    'chapter book',
    'phone',
    'glow stick',
    'candy wrapper',
    'shovel',
    'fork',
    'outlet',
    'lamp',
    'tree',
    'flag',
    'teddies',
    'radio',
    'chocolate',
    'lip gloss',
    'toothpaste',
    'key chain',
    'bow',
    'credit card',
    'tv',
    'thread',
    'clothes',
    'tooth picks',
    'brocolli',
    'ring',
    'photo album',
    'door',
    'leg warmers',
    'cell phone',
    'tomato',
    'bread',
    'cup',
    'lotion',
    'lace',
    'table',
    'book',
    'slipper',
    'tissue box',
    'watch',
    'pen',
    'sailboat',
    'money',
    'bottle cap',
    'bowl',
    'ice cube tray',
    'puddle',
    'toilet',
    'rubber duck',
    'air freshener',
    'CD',
    'boom box',
    'bed',
    'sponge',
    'cinder block',
    'fridge',
    'socks',
    'monitor',
    'milk',
    'sand paper',
    'towel',
    'car',
    'nail file',
    'charger',
    'button',
    'buckle',
    'paper',
    'coasters',
    'glasses',
    'purse',
    'bottle',
    'white out',
    'cat',
    'truck',
    'hair brush',
    'needle',
    'beef',
    'soda can',
    'bag',
    'chair',
    'perfume',
    'thermostat',
    'twister',
    'blanket',
    'face wash',
    'mop',
    'thermometer',
    'street lights',
    'deodorant',
    'pencil',
    'doll',
    'balloon',
    'mirror',
    'flowers',
    'drill press',
    'newspaper',
    'picture frame',
    'couch',
    'magnet',
    'screw',
    'hanger',
    'nail clippers',
    'vase',
    'fake flowers',
    'window',
    'spoon',
    'wagon',
    'zipper',
    'sharpie',
    'desk',
    'carrots',
    'sandal',
    'knife',
    'floor',
    'sun glasses',
    'wallet',
    'pants',
    'towel',
    'money',
    'book',
    'USB drive',
    'grid paper',
    'door',
    'needle',
    'flag',
    'puddle',
    'glasses',
    'socks',
    'sand paper',
    'carrots',
    'chalk',
    'toothbrush',
    'charger',
    'street lights',
    'packing peanuts',
    'shawl',
    'boom box',
    'rusty nail',
    'camera',
    'scotch tape',
    'clothes',
    'hair tie',
    'toilet',
    'food',
    'tomato',
    'window',
    'balloon',
    'button',
    'plastic fork',
    'canvas',
    'mouse pad',
    'magnet',
    'sailboat',
    'video games',
    'rug',
    'air freshener',
    'fridge',
    'glow stick',
    'key chain',
    'teddies',
    'cookie jar',
    'thermometer',
    'lip gloss',
    'sharpie',
    'zipper',
    'floor',
    'tire swing',
    'shirt',
    'helmet',
    'CD',
    'keys',
    'conditioner',
    'table',
    'rubber duck',
    'plate',
    'seat belt',
    'bread',
    'thread',
    'ring',
    'pencil',
    'wallet',
    'screw',
    'remote',
    'ipod',
    'bookmark',
    'outlet',
    'lamp shade',
    'glass',
    'soy sauce packet',
    'soap',
    'bed',
    'watch',
    'cat',
    'nail file',
    'clamp',
    'spring',
    'blanket',
    'credit card',
    'cell phone',
    'tree',
    'mop',
    'car',
    'lotion',
    'leg warmers',
    'candle',
    'picture frame',
    'water bottle',
    'drill press',
    'knife',
    'greeting card',
    'bottle cap',
    'computer',
    'clock',
    'apple',
    'tv',
    'hair brush',
    'television',
    'bowl',
    'playing card',
    'drawer',
    'tissue box',
    'pen',
    'lace',
    'checkbook',
    'doll',
    'monitor',
    'box',
    'bananas',
    'soda can',
    'fake flowers',
    'sticky note',
    'eye liner',
    'purse',
    'buckle',
    'coasters',
    'controller',
    'house',
    'chair',
    'brocolli',
    'cup',
    'cork',
    'thermostat',
    'face wash',
    'newspaper',
    'blouse',
    'twezzers',
    'ice cube tray',
    'radio',
    'chapter book',
    'pool stick',
    'tooth picks',
    'phone',
    'truck',
    'perfume',
    'mirror',
    'toothpaste',
    'model car',
    'keyboard',
    'cinder block',
    'headphones',
    'sponge',
    'fork',
    'speakers',
    'sidewalk',
    'spoon',
    'sun glasses',
    'deodorant',
    'bottle',
    'lamp',
    'rubber band',
    'shovel',
    'flowers',
    'mp3 player',
    'chocolate',
    'couch',
    'washing machine',
    'candy wrapper',
    'sofa',
    'piano',
    'desk',
    'pants',
    'hanger',
    'milk',
    'shampoo',
    'sandal',
    'stockings',
    'paint brush',
    'paper',
    'bow',
    'sketch pad',
    'shoes',
    'clay pot',
    'toe ring',
    'vase',
    'bracelet',
    'photo album',
    'nail clippers',
    'pillow',
    'shoe lace',
    'wagon',
    'beef',
    'eraser',
    'white out',
    'slipper',
    'bag',
    'stop sign',
    'twister',
  ]
  ),]


const conjuctions = [
  'A Shock To',
  'Equivalient To',
  'Similar To',
  'A Breed Of',
  'A Sub-Type Of',
  'A Super-Type Of',
  'A User Of',
  'New To',
  'Experienced With',
]

let physicalEvents = [
  'Birthday',
  'Party',
  'Retardation Party',
  'Wedding',
  'Strip Club',
  'Booty Ball Club'
]

const parts = [
  'ears',
  'eyes',
  'booty',
  'ass',
  'mouth',
]

const relatives = [
  'Mom',
  'Dad',
  'Sister',
  'Crush',
  'Girlfriend',
  'Girlfriend',
  'Girlfriend'
]

function getRandomNumberBetween(min, max) {
  return Math.floor(Math.random() * (max - min + 1) + min);
}


function generateNameNonSense(name) {
  if (name.toLowerCase().includes('adison') || name.toLowerCase().includes('einstein')) {
    return `**_${name}_** was, Is, And Will Be Great Forever!`
  }
  let thing1 = things[Math.floor(Math.random() * things.length)];
  let thing2 = things[Math.floor(Math.random() * things.length)];
  let sentence
  let rand = getRandomNumberBetween(1, 5)
  let part = parts[Math.floor(Math.random() * parts.length)]
  let part2 = parts[Math.floor(Math.random() * parts.length)]
  if (part2 == part) part2 = parts[Math.floor(Math.random() * parts.length)]
  let relative = relatives[Math.floor(Math.random() * relatives.length)]

  if (rand == 1) {
    sentence = `**_${name}_** Is ${conjuctions[Math.floor(Math.random() * conjuctions.length)]} **_${thing1}_**`
  } else if (rand == 2) {
    sentence = `**_${thing1}_** Is **_${name}_**'s **_${thing2}_** In-Spite Of Their ${Math.random() < 0.5 ? 'Big' : 'Small'} Brain`
  } else if (rand == 3) {
    let event = physicalEvents[Math.floor(Math.random() * physicalEvents.length)]
    let thing3 = things[Math.floor(Math.random() * things.length)];

    sentence = `**_${thing1}_** And **_${thing2}_** Went To **_${name}_**'s ${event} And He Was Found Having A ${thing3} Inside His ${part}`
  } else if (rand == 4) {
    sentence = `If **_${thing1}_** and **_${thing2}_** Were To Be Compared, They Would Be ${Math.random() < 0.5 ? 'Bigger' : 'Smaller'} Than **_${name}_**'s ${part}`
  } else if (rand == 5) {
    sentence = `Imagine **_${thing1}_** Being **_${name}_**'s ${part} and **_${thing2}_** Being His ${part2}. Then Do You Think That His Mouth Will Be Full Of His ${relative}'s Cum? ${relative == 'Girlfriend' ? 'Ohh.. Sorry Forgot That ' + name + ' Will Be Single Forever' : ''}`
  }
  return sentence;
}

module.exports = generateNameNonSense