const nhies = [
  "Ask the group the statement shown in the game.",
  "Everyone has to answer and who has done it has to drinkgets a point (depending on what mode you are playing).",
  "Lastly, have a blast playing! I sure did.",
  "Never have I ever quit drinking more than twice.",
  "Never have I ever peed in a pool.",
  "Never have I ever said I was going to go somewhere with no absolutely no intention of actually going.",
  "Never have I ever challenged an animal to a fight.",
  "Never have I ever been kicked out of a bar.",
  "Never have I ever used the bathroom in complete darkness.",
  "Never have I ever been chased by a dog.",
  "Never have I ever worn Crocs.",
  "Never have I ever gotten a tattoo I regret.",
  "Never have I ever called in sick but wasn’t.",
  "Never have I ever kissed an animal.",
  "Never have I ever farted in an elevator and pretended it was not me.",
  "Never have I ever eaten my own bugger.",
  "Never have I ever regifted.",
  "Never have I ever worn a Broken Watch for style.",
  "Never have I ever spent more than $50 on underwear.",
  "Never have I ever pulled a push door.",
  "Never have I ever used the bathroom in complete darkness.",
  "Never have I ever spilled pen ink in my pocket",
  "Never have I ever given someone a black eye.",
  "Never have I ever done something I thought I would never do.",
  "Never have I ever been invited to a threesome.",
  "Never have I ever swam naked in someone else's pool.",
  "Never have I ever gotten drunk playing games like this.",
  "Never have I ever kicked a masseuse during a massage by mistake.",
  "Never have I ever woken up someone with my snoring.",
  "Never have I ever farted while squatting in the gym.",
  "Never have I ever pranked my parents.",
  "Never have I ever tried weed.",
  "Never have I ever driven a car naked",
  "Never have I ever been trapped in an elevator.",
  "Never have I ever sang at karaoke.",
  "Never have I ever used the 5 second rule for food that fell.",
  "Never have I ever dropped my phone in the toilet.",
  "Never have I ever woken up with bruises and not know how they got there.",
  "Never have I ever kissed a stranger.",
  "Never have I ever not cleaned my teeth for over 48 hrs.",
  "Never have I ever dyed my hair the wrong color!",
  "Never have I ever sang out loud in a friends shower.",
  "Never have I ever been locked in a room.",
  "Never have I ever dropped a phone on my face.",
  "Never have I ever been chased by a cat.",
  "Never have I ever gone caroling.",
  "Never have I ever made a snow angel.",
  "Never have I ever ridden a snow sled.",
  "Never have I ever shoveled snow from my driveway.",
  "Never have I ever wished for a Christmas baby.",
  "Never have I ever believed in Santa Claus.",
  "Never have I ever created handmade ornaments.",
  "Never have I ever spent Christmas alone.",
  "Never have I ever dressed my family in matching Christmas outfits.",
  "Never have I ever created an ugly Christmas sweater.",
  "Never have I ever cut down my own Christmas Tree.",
  "Never have I ever filled stockings for Christmas.",
  "Never have I ever been a Secret Santa.",
  "Never have I ever hosted the annual Christmas party.",
  "Never have I ever watched the new year celebration lights.",
  "Never have I ever bought my pet a present.",
  "Never have I ever given or received gifts for the 12 days of Christmas.",
  "Never have I ever had a white Christmas.",
  "Never have I ever given food to a homeless shelter.",
  "Never have I ever slept in until after midday on Christmas",
  "Never have I ever accidentally pulled down a Christmas.",
  "Never have I ever celebrated Christmas.",
  "Never have I ever worked on Christmas Eve.",
  "Never have I ever given someone a gift and they cried.",
  "Never have I ever dreaded Christmas Cleaning.",
  "Never have I ever baked my own cake on Christmas.",
  "Never have I ever burned the family Christmas Dinner.",
  "Never have I ever baked my own ham.",
  "Never have I ever been snowed in.",
  "Never have I ever taken a sexy selfie.",
  "Never Have I ever rainbow kissed.",
  "Never have I ever sent a dirty text to the wrong person.",
  "Never have I ever had a one night stand.",
  "Never have I ever done it in the sea.",
  "Never have I ever shaved my partner’s pubic hair.",
  "Never have I ever kissed a celebrity.",
  "Never have I ever put a thumb in it.",
  "Never have I ever abandoned my baby mama.",
  "Never have I ever tasted myself.",
  "Never have I ever watched a friend (do it).",
  "Never have I ever cheated.",
  "Never have I ever done it while a family member was in the same room.",
  "Never have I ever touched myself to a Youtube video.",
  "Never have I ever had to use lubrication.",
  "Never have I ever had to fake it.",
  "Never have I ever tossed the salad.",
  "Never have I ever Squirted.",
  "Never have I ever flashed a bartender for a free drink.",
  "Never have I ever done it in a public place.",
  "Never have I ever been in handcuffs, for any reason.",
  "Never have I ever done it on my period.",
  "Never have I ever licked food off someone.",
  "Never have I ever done it on a kitchen counter.",
  "Never have I ever been with someone 10 inches or longer.",
  "Never have I ever showered with the same sex.",
  "Never have I ever slept with twins.",
  "Never have I ever caught my parents doing it.",
  "Never have I ever been choked.",
  "Never have I ever stalked an ex online.",
  "Never have I ever sucked my partners toes.",
  "Never have I ever screwed around in an elevator.",
  "Never have I ever slept with someone within an hour of meeting them.",
  "Never have I ever had an STD.",
  "Never have I ever givenreceived a lap dance.",
  "Never have I ever required medical attention due to a foreign object stuck inside my body.",
  "Never have I ever been upset with a partner for not performing well.",
  "Never have I ever used a friends pleasure toys.",
  "Never have I ever sent someone a picture of my stuff.",
  "Never have I ever been kicked out of a bar.",
  "Never have I ever thrown up and swallow it.",
  "Never have I ever Skinny Dipped.",
  "Never have I ever taken the morning after pill.",
  "Never have I ever driven through red lights.",
  "Never have I ever stalked my Ex.",
  "Never have I ever checked through my phone media to remember the night before.",
  "Never have I ever farted in an elevator and pretended it was not me.",
  "Never have I ever put a thumb in it.",
  "Never have I ever had a sugar daddy.",
  "Never have I ever went to work without bathing.",
  "Never have I ever created an Instagram just to stalk people.",
  "Never have I ever accepted a drop from total strangers.",
  "Never have I ever eaten raw fish.",
  "Never have I ever tasted myself.",
  "Never have I ever watched a friend (do it).",
  "Never have I ever done it with a family member in the same building.",
  "Never have I ever said I am never drinking again.",
  "Never have I ever made a wish after seeing a falling star.",
  "Never have I ever been to be the Tooth Fairy.",
  "Never have I ever coughed on my boss.",
  "Never have I ever shot a person by accident.",
  "Never have I ever kissed a celebrity.",
  "Never have I ever liked a book to movie adaptation more than the book.",
  "Never have I ever cut my own hair.",
  "Never have I ever been to (2) or more nightclubs in one night.",
  "Never have I ever crushed on a celebrity.",
  "Never have I ever used Facebook.",
  "Never have I ever smoked any substance.",
  "Never have I ever tried a BuzzFeed recipe.",
  "Never have I ever been chased by a cat.",
  "Never have I ever cooked outdoors.",
  "Never have I ever hosted a barbecue.",
  "Never have I ever done body shots.",
  "Never have I ever slept with my pet.",
  "Never have I ever danced on a bar.",
  "Never have I ever tasted breast milk.",
  "Never have I ever tried bathing in a fountain.",
  "Never have I ever slipped on nothing.",
  "Never have I ever been to the circus.",
  "Never have I ever used an emoji when texting.",
  "Never have I ever built A Snow Man.",
  "Never have I ever lost weight from stress.",
  "Never have I ever been walked in on by someone;",
  "Never have I ever ridden a motorcycle;",
  "Never have I ever walked into a glass window;",
  "Never have I ever been in handcuffs, for any reason;",
  "Never have I ever been locked in a room for more than an hour;",
  "Never have I ever started a fight;",
  "Never have I ever peed in the shower;",
  "Never have I ever voted for Trump;",
  "Never have I ever fell asleep on the bus and missed my stop;",
  "Never have I ever set something on fire (people included);",
  "Never have I ever played beer pong;",
  "Never have I ever held a gun;",
  "Never have I ever sniffed marker ink;",
  "Never have I ever pulled a push door;",
  "Never have I ever laughed so hard I peed a little;",
  "Never have I ever gone without a bath or shower for more than a week;",
  "Never have I ever picked at a wedgie in public;",
  "Never have I ever thrown up because someone else threw up;",
  "Never have I ever made a prank phone call.",
  "Never have I ever set something on fire (people included).",
  "Never have I ever tasted cat food.",
  "Never have I ever sharted.",
  "Never have I ever been bungee jumping.",
  "Never have I ever been sneezed on.",
  "Never have I ever gone commando.",
  "Never have I ever slipped and fell on nothing.",
  "Never have I ever had sushi.",
  "Never have I ever shot a person by accident.",
  "Never have I ever used the bathroom in complete darkness.",
  "Never have I ever sent my food back to the chef.",
  "Never have I ever accepted a drop from total strangers.",
  "Never have I ever crushed on a celebrity.",
  "Never have I ever been chased by a dog.",
  "Never have I ever changed a car tire.",
  "Never have I ever done body shots.",
  "Never have I ever won a game of Monopoly.",
  "Never have I ever kissed an animal.",
  "Never have I ever been to the circus.",
  "Never have I ever cheated on a test.",
  "Never have I ever been on TV.",
  "Never have I ever fallen asleep in the cinema.",
  "Never have I ever been to (2) or more nightclubs in one night.",
  "Never have I ever teased an army official.",
  "Never have I ever measured my junk.",
  "Never have I ever done something totally stupid and broke a bone.",
  "Never have I ever driven before I had my license.",
  "Never have I ever tried dancing like Michael Jackson.",
  "Never have I ever messed with the watchman.",
  "Never have I ever set my house on fire.",
  "Never have I ever hit someone for no reason.",
  "Never have I ever frightened someone using the deepness of my voice.",
  "Never have I ever tripped someone in public.",
  "Never have I ever shouted to hear my echo.",
  "Never have I ever farted in a closed space and watched others squeal.",
  "Never have I ever stolen alcohol from the kitchen.",
  "Never have I ever damaged my parent's vehicle and fixed it on the same night.",
  "Never have I ever chased down an animal while driving.",
  "Never have I ever gone commando.",
  "Never have I ever flirted with a much older lady.",
  "Never have I ever been caught 'doing it'.",
  "Never have I ever ran across the road to avoid a car.",
  "Never have I ever fallen asleep on my partner while watching TV.",
  "Never have I ever peed in the shower.",
  "Never have I ever laughed until I threw up.",
  "Never have I ever done an adrenaline junkie activity with my partner like skydiving.",
  "Never have I ever used Tinder.",
  "Never have I ever tried speed dating.",
  "Never have I ever dated someone I was told to date by friends.",
  "Never have I ever been stressed by my partner.",
  "Never have I ever done a double date.",
  "Never have I ever dreamed about my wedding day.",
  "Never have I ever eaten only ice cream for a whole day.",
  "Never have I ever tried to change my partner's phone to an iPhone.",
  "Never have I ever tried to impress someone who hates me.",
  "Never have I ever cheated.",
  "Never have I ever traveled with a significant other.",
  "Never have I ever dinned and dashed with a significant other.",
  "Never have I ever thrown up on a friend.",
  "Never have I ever laughed so hard I sharted.",
  "Never have I ever had a picnic date.",
  "Never have I ever played two truths ad a lie with as a conversation starter.",
];

const getNhie = () => {
  return nhies[Math.floor(Math.random() * nhies.length)]
    .replaceAll(" i ", " You ")
    .replaceAll(" I ", " You ")
    .replaceAll(" myself ", " yourself ")
    .replaceAll(" myself", " yourself")
    .replaceAll(" my ", " you ");
};

module.exports = getNhie;
