const nhies = [
  "Never have I ever accidentally sent a text to the wrong person and pretended it was intentional.",
  "Never have I ever read a book or watched a movie just for the steamy scenes.",
  "Never have I ever tried to impress someone with a fancy dinner I secretly ordered from a restaurant.",
  "Never have I ever gone on a date just for the free food.",
  "Never have I ever ghosted someone after a first date.",
  "Never have I ever used a cheesy pickup line on someone.",
  "Never have I ever gone skinny dipping.",
  "Never have I ever accidentally walked in on someone in a compromising situation.",
  "Never have I ever flirted with someone just to get a discount.",
  "Never have I ever lied about my age to impress someone.",
  "Never have I ever sent a risky text and immediately regretted it.",
  "Never have I ever stalked someone on social media.",
  "Never have I ever kissed someone on the first date.",
  "Never have I ever pretended to know more about something just to impress someone.",
  "Never have I ever had a crush on a friend's parent.",
  "Never have I ever used a dating app just for fun without any intention of meeting anyone.",
  "Never have I ever accidentally liked someone's old social media post while stalking them.",
  "Never have I ever fantasized about being in a romantic comedy-style love triangle.",
  "Never have I ever been caught checking out someone's butt.",
  "Never have I ever had a one-night stand.",
  "Never have I ever received a suggestive text from someone and pretended I didn't understand it.",
  "Never have I ever lied about my relationship status to avoid someone's advances.",
  "Never have I ever accidentally sent a flirty text to my boss instead of my significant other.",
  "Never have I ever pretended to be interested in someone's hobbies just to impress them.",
  "Never have I ever been caught making out in a public place.",
  "Never have I ever used a fake name at a bar or club.",
  "Never have I ever forgotten someone's name right after meeting them.",
  "Never have I ever flirted with someone just to make someone else jealous.",
  "Never have I ever been caught taking a selfie.",
  "Never have I ever had a crush on a celebrity.",
  "Never have I ever swiped right on someone on a dating app without reading their profile.",
  "Never have I ever pretended to be sick to avoid going on a date.",
  "Never have I ever lied about being in a relationship to get out of a date.",
  "Never have I ever used a cheesy pickup line on a dating app.",
  "Never have I ever accidentally sent a text meant for someone else to a family member.",
  "Never have I ever been caught snooping through someone's phone.",
  "Never have I ever had a crush on a teacher.",
  "Never have I ever lied about my occupation to impress someone.",
  "Never have I ever pretended to have read a book or watched a movie just to impress someone.",
  "Never have I ever had a crush on a coworker.",
  "Never have I ever gone on a date just for the free drinks.",
  "Never have I ever had a crush on a fictional character.",
  "Never have I ever flirted with someone just to get something for free.",
  "Never have I ever been caught checking out someone's cleavage.",
  "Never have I ever gone on a blind date.",
  "Never have I ever been caught Googling someone before a date.",
  "Never have I ever pretended to be interested in something just to impress someone.",
  "Never have I ever had a crush on a friend's sibling.",
  "Never have I ever had a crush on a friend's ex.",
  "Never have I ever pretended to be someone else on social media.",
  "Never have I ever faked a laugh at someone's joke just to impress them.",
  "Never have I ever accidentally sent a text about someone to that person.",
  "Never have I ever had a crush on a boss or supervisor.",
  "Never have I ever tried to slide into someone's DMs unsuccessfully.",
  "Never have I ever flirted with someone just to get out of trouble.",
  "Never have I ever had a crush on a neighbor.",
  "Never have I ever flirted with someone just to get a discount.",
  "Never have I ever pretended to know a celebrity just to impress someone.",
  "Never have I ever been caught taking a mirror selfie.",
  "Never have I ever lied about my relationship status to avoid commitment.",
  "Never have I ever flirted with someone to get a better deal on something.",
  "Never have I ever fantasized about a coworker.",
  "Never have I ever used a fake name at a restaurant.",
  "Never have I ever lied about my age to get into a bar or club.",
  "Never have I ever sent a suggestive text to the wrong person.",
  "Never have I ever had a crush on a friend's significant other.",
  "Never have I ever flirted with someone just to make someone else jealous.",
  "Never have I ever pretended to be someone else online.",
  "Never have I ever had a crush on a friend's parent.",
  "Never have I ever pretended to be interested in someone's hobbies just to impress them.",
  "Never have I ever lied about my occupation to impress someone.",
  "Never have I ever pretended to have read a book or watched a movie just to impress someone.",
  "Never have I ever faked a laugh at someone's joke just to impress them.",
  "Never have I ever pretended to know a celebrity just to impress someone.",
  "Never have I ever lied about my relationship status to avoid commitment.",
  "Never have I ever flirted with someone to get a better deal on something.",
  "Never have I ever fantasized about a coworker.",
  "Never have I ever used a fake name at a restaurant.",
  "Never have I ever lied about my age to get into a bar or club.",
  "Never have I ever flirted with someone just to make someone else jealous.",
  "Never have I ever pretended to be someone else online."
];


const getNhie = () => {
  return nhies[Math.floor(Math.random() * nhies.length)]
    .replaceAll(" i ", " You ")
    .replaceAll(" I ", " You ")
    .replaceAll(" myself ", " yourself ")
    .replaceAll(" myself", " yourself")
    .replaceAll(" my ", " you ");
};

module.exports = getNhie;
